"""Prediction API for the diabetes risk indicator.

Serves the model trained by train_model.py. Start it from the project root:

    uvicorn 03_api_development:app --reload

Step 3 of the pipeline: 01 EDA -> 02 model engineering -> 03 API -> 04 Streamlit app.
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

MODEL_PATH = Path(__file__).resolve().parent / "models" / "diabetes_model.joblib"

DISCLAIMER = (
    "This estimate is generated by a statistical model trained on self-reported "
    "CDC BRFSS 2015 survey data. It is not a medical diagnosis and cannot account "
    "for your full health history. Please consult a healthcare professional for an "
    "accurate assessment."
)

app = FastAPI(
    title="Diabetes Risk Indicator API",
    description="Estimates diabetes risk category from self-reported health factors.",
    version="1.0.0",
)


def load_bundle():
    if not MODEL_PATH.exists():
        raise RuntimeError(
            f"Model file not found at {MODEL_PATH}. Run `python train_model.py` first."
        )
    return joblib.load(MODEL_PATH)


bundle = load_bundle()
model = bundle["model"]
scaler = bundle["scaler"]
FEATURES = bundle["features"]
LABELS = bundle["labels"]


class PredictionRequest(BaseModel):
    """One person's self-reported health factors.

    Field constraints mirror the BRFSS survey encodings, so out-of-range input is
    rejected with a clear 422 instead of silently producing a nonsense prediction.
    """

    HighBP: int = Field(..., ge=0, le=1, description="Told they have high blood pressure")
    HighChol: int = Field(..., ge=0, le=1, description="Told they have high cholesterol")
    BMI: float = Field(..., ge=10, le=100, description="Body Mass Index")
    HeartDiseaseorAttack: int = Field(..., ge=0, le=1, description="Heart disease or heart attack")
    GenHlth: int = Field(..., ge=1, le=5, description="General health, 1 = excellent to 5 = poor")
    PhysHlth: int = Field(..., ge=0, le=30, description="Days of poor physical health in last 30")
    DiffWalk: int = Field(..., ge=0, le=1, description="Serious difficulty walking or climbing stairs")
    Age: int = Field(..., ge=1, le=13, description="BRFSS age bracket, 1 = 18-24 to 13 = 80+")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "HighBP": 1, "HighChol": 1, "BMI": 32.0,
                    "HeartDiseaseorAttack": 0, "GenHlth": 4,
                    "PhysHlth": 10, "DiffWalk": 1, "Age": 9,
                }
            ]
        }
    }


class PredictionResponse(BaseModel):
    predicted_label: str
    probabilities: dict[str, float]
    disclaimer: str


@app.get("/")
def root():
    return {"status": "ok", "docs": "/docs", "predict": "POST /predict"}


@app.get("/health")
def health():
    return {"status": "healthy", "model_loaded": model is not None, "features": FEATURES}


@app.post("/predict", response_model=PredictionResponse)
def predict(request: PredictionRequest):
    payload = request.model_dump()

    # Build the row in the exact order the model was trained on. Relying on dict
    # ordering here would be a silent correctness bug if the schema ever changed.
    # A named DataFrame (rather than a bare array) lets scikit-learn verify the
    # column names against the ones the scaler was fitted on.
    try:
        row = pd.DataFrame(
            [[float(payload[name]) for name in FEATURES]], columns=FEATURES
        )
    except KeyError as exc:
        raise HTTPException(status_code=500, detail=f"Missing feature: {exc}") from exc

    # Apply the SAME scaler fitted during training — the model only understands
    # scaled input.
    row_scaled = scaler.transform(row)

    probabilities = model.predict_proba(row_scaled)[0]
    predicted_class = int(np.argmax(probabilities))

    return PredictionResponse(
        predicted_label=LABELS[predicted_class],
        probabilities={
            LABELS[int(cls)]: round(float(prob), 4)
            for cls, prob in zip(model.classes_, probabilities)
        },
        disclaimer=DISCLAIMER,
    )
